---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-{{ .Values.alertmanager.name }}
  namespace: {{ .Release.Namespace }} 
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1m
      receiver: 'prom2teams'
    receivers:
    - name: 'prom2teams'
      webhook_configs:
      - url: 'http://prom2teams:8089/'