---
apiVersion: v1
kind: Secret
metadata:
  name: istio-certs
  namespace: {{ .Release.Namespace }}  
data:
  cert-chain.pem: "{{ .Values.istio_cert.cert_chain }}"
  key.pem: "{{ .Values.istio_cert.key }}"
  root-cert.pem: "{{ .Values.istio_cert.root_cert }}"