---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheus.name }}-maistra-view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicemeshmemberrolls.maistra.io-v1-view