---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-operator-resources
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["catalogsources", "subscriptions", "installplans","operatorgroups"]
  verbs: ["list", "watch", "get"]
...