---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-monitoring-prometheus
  namespace: {{ .Release.Namespace }}
stringData:
  basicAuthPassword: {{ .Values.secrets.basicAuthPassword }}
type: Opaque